// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messages.proto

package com.nclab.chl848.t3android;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface T3PlayerDataMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:T3PlayerDataMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string playerName = 1;</code>
     */
    java.lang.String getPlayerName();
    /**
     * <code>optional string playerName = 1;</code>
     */
    com.google.protobuf.ByteString
        getPlayerNameBytes();

    /**
     * <code>optional int32 playerId = 2;</code>
     */
    int getPlayerId();
  }
  /**
   * Protobuf type {@code T3PlayerDataMessage}
   */
  public  static final class T3PlayerDataMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:T3PlayerDataMessage)
      T3PlayerDataMessageOrBuilder {
    // Use T3PlayerDataMessage.newBuilder() to construct.
    private T3PlayerDataMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private T3PlayerDataMessage() {
      playerName_ = "";
      playerId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private T3PlayerDataMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              playerName_ = s;
              break;
            }
            case 16: {

              playerId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nclab.chl848.t3android.Message.internal_static_T3PlayerDataMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nclab.chl848.t3android.Message.internal_static_T3PlayerDataMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nclab.chl848.t3android.Message.T3PlayerDataMessage.class, com.nclab.chl848.t3android.Message.T3PlayerDataMessage.Builder.class);
    }

    public static final int PLAYERNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object playerName_;
    /**
     * <code>optional string playerName = 1;</code>
     */
    public java.lang.String getPlayerName() {
      java.lang.Object ref = playerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playerName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string playerName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPlayerNameBytes() {
      java.lang.Object ref = playerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLAYERID_FIELD_NUMBER = 2;
    private int playerId_;
    /**
     * <code>optional int32 playerId = 2;</code>
     */
    public int getPlayerId() {
      return playerId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPlayerNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, playerName_);
      }
      if (playerId_ != 0) {
        output.writeInt32(2, playerId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPlayerNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, playerName_);
      }
      if (playerId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, playerId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.nclab.chl848.t3android.Message.T3PlayerDataMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nclab.chl848.t3android.Message.T3PlayerDataMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nclab.chl848.t3android.Message.T3PlayerDataMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nclab.chl848.t3android.Message.T3PlayerDataMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nclab.chl848.t3android.Message.T3PlayerDataMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.nclab.chl848.t3android.Message.T3PlayerDataMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.nclab.chl848.t3android.Message.T3PlayerDataMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.nclab.chl848.t3android.Message.T3PlayerDataMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.nclab.chl848.t3android.Message.T3PlayerDataMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.nclab.chl848.t3android.Message.T3PlayerDataMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nclab.chl848.t3android.Message.T3PlayerDataMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code T3PlayerDataMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:T3PlayerDataMessage)
        com.nclab.chl848.t3android.Message.T3PlayerDataMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nclab.chl848.t3android.Message.internal_static_T3PlayerDataMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nclab.chl848.t3android.Message.internal_static_T3PlayerDataMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nclab.chl848.t3android.Message.T3PlayerDataMessage.class, com.nclab.chl848.t3android.Message.T3PlayerDataMessage.Builder.class);
      }

      // Construct using com.nclab.chl848.t3android.Message.T3PlayerDataMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        playerName_ = "";

        playerId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nclab.chl848.t3android.Message.internal_static_T3PlayerDataMessage_descriptor;
      }

      public com.nclab.chl848.t3android.Message.T3PlayerDataMessage getDefaultInstanceForType() {
        return com.nclab.chl848.t3android.Message.T3PlayerDataMessage.getDefaultInstance();
      }

      public com.nclab.chl848.t3android.Message.T3PlayerDataMessage build() {
        com.nclab.chl848.t3android.Message.T3PlayerDataMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.nclab.chl848.t3android.Message.T3PlayerDataMessage buildPartial() {
        com.nclab.chl848.t3android.Message.T3PlayerDataMessage result = new com.nclab.chl848.t3android.Message.T3PlayerDataMessage(this);
        result.playerName_ = playerName_;
        result.playerId_ = playerId_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nclab.chl848.t3android.Message.T3PlayerDataMessage) {
          return mergeFrom((com.nclab.chl848.t3android.Message.T3PlayerDataMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nclab.chl848.t3android.Message.T3PlayerDataMessage other) {
        if (other == com.nclab.chl848.t3android.Message.T3PlayerDataMessage.getDefaultInstance()) return this;
        if (!other.getPlayerName().isEmpty()) {
          playerName_ = other.playerName_;
          onChanged();
        }
        if (other.getPlayerId() != 0) {
          setPlayerId(other.getPlayerId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.nclab.chl848.t3android.Message.T3PlayerDataMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.nclab.chl848.t3android.Message.T3PlayerDataMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object playerName_ = "";
      /**
       * <code>optional string playerName = 1;</code>
       */
      public java.lang.String getPlayerName() {
        java.lang.Object ref = playerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          playerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string playerName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPlayerNameBytes() {
        java.lang.Object ref = playerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string playerName = 1;</code>
       */
      public Builder setPlayerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        playerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string playerName = 1;</code>
       */
      public Builder clearPlayerName() {
        
        playerName_ = getDefaultInstance().getPlayerName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string playerName = 1;</code>
       */
      public Builder setPlayerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        playerName_ = value;
        onChanged();
        return this;
      }

      private int playerId_ ;
      /**
       * <code>optional int32 playerId = 2;</code>
       */
      public int getPlayerId() {
        return playerId_;
      }
      /**
       * <code>optional int32 playerId = 2;</code>
       */
      public Builder setPlayerId(int value) {
        
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 playerId = 2;</code>
       */
      public Builder clearPlayerId() {
        
        playerId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:T3PlayerDataMessage)
    }

    // @@protoc_insertion_point(class_scope:T3PlayerDataMessage)
    private static final com.nclab.chl848.t3android.Message.T3PlayerDataMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nclab.chl848.t3android.Message.T3PlayerDataMessage();
    }

    public static com.nclab.chl848.t3android.Message.T3PlayerDataMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<T3PlayerDataMessage>
        PARSER = new com.google.protobuf.AbstractParser<T3PlayerDataMessage>() {
      public T3PlayerDataMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new T3PlayerDataMessage(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<T3PlayerDataMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<T3PlayerDataMessage> getParserForType() {
      return PARSER;
    }

    public com.nclab.chl848.t3android.Message.T3PlayerDataMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface T3StartNewGameMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:T3StartNewGameMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 initPlayerId = 1;</code>
     */
    int getInitPlayerId();
  }
  /**
   * Protobuf type {@code T3StartNewGameMessage}
   */
  public  static final class T3StartNewGameMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:T3StartNewGameMessage)
      T3StartNewGameMessageOrBuilder {
    // Use T3StartNewGameMessage.newBuilder() to construct.
    private T3StartNewGameMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private T3StartNewGameMessage() {
      initPlayerId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private T3StartNewGameMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              initPlayerId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nclab.chl848.t3android.Message.internal_static_T3StartNewGameMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nclab.chl848.t3android.Message.internal_static_T3StartNewGameMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nclab.chl848.t3android.Message.T3StartNewGameMessage.class, com.nclab.chl848.t3android.Message.T3StartNewGameMessage.Builder.class);
    }

    public static final int INITPLAYERID_FIELD_NUMBER = 1;
    private int initPlayerId_;
    /**
     * <code>optional int32 initPlayerId = 1;</code>
     */
    public int getInitPlayerId() {
      return initPlayerId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (initPlayerId_ != 0) {
        output.writeInt32(1, initPlayerId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (initPlayerId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, initPlayerId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.nclab.chl848.t3android.Message.T3StartNewGameMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nclab.chl848.t3android.Message.T3StartNewGameMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nclab.chl848.t3android.Message.T3StartNewGameMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nclab.chl848.t3android.Message.T3StartNewGameMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nclab.chl848.t3android.Message.T3StartNewGameMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.nclab.chl848.t3android.Message.T3StartNewGameMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.nclab.chl848.t3android.Message.T3StartNewGameMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.nclab.chl848.t3android.Message.T3StartNewGameMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.nclab.chl848.t3android.Message.T3StartNewGameMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.nclab.chl848.t3android.Message.T3StartNewGameMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nclab.chl848.t3android.Message.T3StartNewGameMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code T3StartNewGameMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:T3StartNewGameMessage)
        com.nclab.chl848.t3android.Message.T3StartNewGameMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nclab.chl848.t3android.Message.internal_static_T3StartNewGameMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nclab.chl848.t3android.Message.internal_static_T3StartNewGameMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nclab.chl848.t3android.Message.T3StartNewGameMessage.class, com.nclab.chl848.t3android.Message.T3StartNewGameMessage.Builder.class);
      }

      // Construct using com.nclab.chl848.t3android.Message.T3StartNewGameMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        initPlayerId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nclab.chl848.t3android.Message.internal_static_T3StartNewGameMessage_descriptor;
      }

      public com.nclab.chl848.t3android.Message.T3StartNewGameMessage getDefaultInstanceForType() {
        return com.nclab.chl848.t3android.Message.T3StartNewGameMessage.getDefaultInstance();
      }

      public com.nclab.chl848.t3android.Message.T3StartNewGameMessage build() {
        com.nclab.chl848.t3android.Message.T3StartNewGameMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.nclab.chl848.t3android.Message.T3StartNewGameMessage buildPartial() {
        com.nclab.chl848.t3android.Message.T3StartNewGameMessage result = new com.nclab.chl848.t3android.Message.T3StartNewGameMessage(this);
        result.initPlayerId_ = initPlayerId_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nclab.chl848.t3android.Message.T3StartNewGameMessage) {
          return mergeFrom((com.nclab.chl848.t3android.Message.T3StartNewGameMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nclab.chl848.t3android.Message.T3StartNewGameMessage other) {
        if (other == com.nclab.chl848.t3android.Message.T3StartNewGameMessage.getDefaultInstance()) return this;
        if (other.getInitPlayerId() != 0) {
          setInitPlayerId(other.getInitPlayerId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.nclab.chl848.t3android.Message.T3StartNewGameMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.nclab.chl848.t3android.Message.T3StartNewGameMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int initPlayerId_ ;
      /**
       * <code>optional int32 initPlayerId = 1;</code>
       */
      public int getInitPlayerId() {
        return initPlayerId_;
      }
      /**
       * <code>optional int32 initPlayerId = 1;</code>
       */
      public Builder setInitPlayerId(int value) {
        
        initPlayerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 initPlayerId = 1;</code>
       */
      public Builder clearInitPlayerId() {
        
        initPlayerId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:T3StartNewGameMessage)
    }

    // @@protoc_insertion_point(class_scope:T3StartNewGameMessage)
    private static final com.nclab.chl848.t3android.Message.T3StartNewGameMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nclab.chl848.t3android.Message.T3StartNewGameMessage();
    }

    public static com.nclab.chl848.t3android.Message.T3StartNewGameMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<T3StartNewGameMessage>
        PARSER = new com.google.protobuf.AbstractParser<T3StartNewGameMessage>() {
      public T3StartNewGameMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new T3StartNewGameMessage(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<T3StartNewGameMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<T3StartNewGameMessage> getParserForType() {
      return PARSER;
    }

    public com.nclab.chl848.t3android.Message.T3StartNewGameMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface T3PlayerMoveMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:T3PlayerMoveMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 playerId = 1;</code>
     */
    int getPlayerId();

    /**
     * <code>optional int32 tileNum = 2;</code>
     */
    int getTileNum();
  }
  /**
   * Protobuf type {@code T3PlayerMoveMessage}
   */
  public  static final class T3PlayerMoveMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:T3PlayerMoveMessage)
      T3PlayerMoveMessageOrBuilder {
    // Use T3PlayerMoveMessage.newBuilder() to construct.
    private T3PlayerMoveMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private T3PlayerMoveMessage() {
      playerId_ = 0;
      tileNum_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private T3PlayerMoveMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              playerId_ = input.readInt32();
              break;
            }
            case 16: {

              tileNum_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nclab.chl848.t3android.Message.internal_static_T3PlayerMoveMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nclab.chl848.t3android.Message.internal_static_T3PlayerMoveMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nclab.chl848.t3android.Message.T3PlayerMoveMessage.class, com.nclab.chl848.t3android.Message.T3PlayerMoveMessage.Builder.class);
    }

    public static final int PLAYERID_FIELD_NUMBER = 1;
    private int playerId_;
    /**
     * <code>optional int32 playerId = 1;</code>
     */
    public int getPlayerId() {
      return playerId_;
    }

    public static final int TILENUM_FIELD_NUMBER = 2;
    private int tileNum_;
    /**
     * <code>optional int32 tileNum = 2;</code>
     */
    public int getTileNum() {
      return tileNum_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (playerId_ != 0) {
        output.writeInt32(1, playerId_);
      }
      if (tileNum_ != 0) {
        output.writeInt32(2, tileNum_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (playerId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, playerId_);
      }
      if (tileNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, tileNum_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.nclab.chl848.t3android.Message.T3PlayerMoveMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nclab.chl848.t3android.Message.T3PlayerMoveMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nclab.chl848.t3android.Message.T3PlayerMoveMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nclab.chl848.t3android.Message.T3PlayerMoveMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nclab.chl848.t3android.Message.T3PlayerMoveMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.nclab.chl848.t3android.Message.T3PlayerMoveMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.nclab.chl848.t3android.Message.T3PlayerMoveMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.nclab.chl848.t3android.Message.T3PlayerMoveMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.nclab.chl848.t3android.Message.T3PlayerMoveMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.nclab.chl848.t3android.Message.T3PlayerMoveMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nclab.chl848.t3android.Message.T3PlayerMoveMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code T3PlayerMoveMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:T3PlayerMoveMessage)
        com.nclab.chl848.t3android.Message.T3PlayerMoveMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nclab.chl848.t3android.Message.internal_static_T3PlayerMoveMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nclab.chl848.t3android.Message.internal_static_T3PlayerMoveMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nclab.chl848.t3android.Message.T3PlayerMoveMessage.class, com.nclab.chl848.t3android.Message.T3PlayerMoveMessage.Builder.class);
      }

      // Construct using com.nclab.chl848.t3android.Message.T3PlayerMoveMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        playerId_ = 0;

        tileNum_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nclab.chl848.t3android.Message.internal_static_T3PlayerMoveMessage_descriptor;
      }

      public com.nclab.chl848.t3android.Message.T3PlayerMoveMessage getDefaultInstanceForType() {
        return com.nclab.chl848.t3android.Message.T3PlayerMoveMessage.getDefaultInstance();
      }

      public com.nclab.chl848.t3android.Message.T3PlayerMoveMessage build() {
        com.nclab.chl848.t3android.Message.T3PlayerMoveMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.nclab.chl848.t3android.Message.T3PlayerMoveMessage buildPartial() {
        com.nclab.chl848.t3android.Message.T3PlayerMoveMessage result = new com.nclab.chl848.t3android.Message.T3PlayerMoveMessage(this);
        result.playerId_ = playerId_;
        result.tileNum_ = tileNum_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nclab.chl848.t3android.Message.T3PlayerMoveMessage) {
          return mergeFrom((com.nclab.chl848.t3android.Message.T3PlayerMoveMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nclab.chl848.t3android.Message.T3PlayerMoveMessage other) {
        if (other == com.nclab.chl848.t3android.Message.T3PlayerMoveMessage.getDefaultInstance()) return this;
        if (other.getPlayerId() != 0) {
          setPlayerId(other.getPlayerId());
        }
        if (other.getTileNum() != 0) {
          setTileNum(other.getTileNum());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.nclab.chl848.t3android.Message.T3PlayerMoveMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.nclab.chl848.t3android.Message.T3PlayerMoveMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int playerId_ ;
      /**
       * <code>optional int32 playerId = 1;</code>
       */
      public int getPlayerId() {
        return playerId_;
      }
      /**
       * <code>optional int32 playerId = 1;</code>
       */
      public Builder setPlayerId(int value) {
        
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 playerId = 1;</code>
       */
      public Builder clearPlayerId() {
        
        playerId_ = 0;
        onChanged();
        return this;
      }

      private int tileNum_ ;
      /**
       * <code>optional int32 tileNum = 2;</code>
       */
      public int getTileNum() {
        return tileNum_;
      }
      /**
       * <code>optional int32 tileNum = 2;</code>
       */
      public Builder setTileNum(int value) {
        
        tileNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 tileNum = 2;</code>
       */
      public Builder clearTileNum() {
        
        tileNum_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:T3PlayerMoveMessage)
    }

    // @@protoc_insertion_point(class_scope:T3PlayerMoveMessage)
    private static final com.nclab.chl848.t3android.Message.T3PlayerMoveMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nclab.chl848.t3android.Message.T3PlayerMoveMessage();
    }

    public static com.nclab.chl848.t3android.Message.T3PlayerMoveMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<T3PlayerMoveMessage>
        PARSER = new com.google.protobuf.AbstractParser<T3PlayerMoveMessage>() {
      public T3PlayerMoveMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new T3PlayerMoveMessage(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<T3PlayerMoveMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<T3PlayerMoveMessage> getParserForType() {
      return PARSER;
    }

    public com.nclab.chl848.t3android.Message.T3PlayerMoveMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface T3GameFinishedMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:T3GameFinishedMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 winnerId = 1;</code>
     */
    int getWinnerId();
  }
  /**
   * Protobuf type {@code T3GameFinishedMessage}
   */
  public  static final class T3GameFinishedMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:T3GameFinishedMessage)
      T3GameFinishedMessageOrBuilder {
    // Use T3GameFinishedMessage.newBuilder() to construct.
    private T3GameFinishedMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private T3GameFinishedMessage() {
      winnerId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private T3GameFinishedMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              winnerId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nclab.chl848.t3android.Message.internal_static_T3GameFinishedMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nclab.chl848.t3android.Message.internal_static_T3GameFinishedMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nclab.chl848.t3android.Message.T3GameFinishedMessage.class, com.nclab.chl848.t3android.Message.T3GameFinishedMessage.Builder.class);
    }

    public static final int WINNERID_FIELD_NUMBER = 1;
    private int winnerId_;
    /**
     * <code>optional int32 winnerId = 1;</code>
     */
    public int getWinnerId() {
      return winnerId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (winnerId_ != 0) {
        output.writeInt32(1, winnerId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (winnerId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, winnerId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.nclab.chl848.t3android.Message.T3GameFinishedMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nclab.chl848.t3android.Message.T3GameFinishedMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nclab.chl848.t3android.Message.T3GameFinishedMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nclab.chl848.t3android.Message.T3GameFinishedMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nclab.chl848.t3android.Message.T3GameFinishedMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.nclab.chl848.t3android.Message.T3GameFinishedMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.nclab.chl848.t3android.Message.T3GameFinishedMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.nclab.chl848.t3android.Message.T3GameFinishedMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.nclab.chl848.t3android.Message.T3GameFinishedMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.nclab.chl848.t3android.Message.T3GameFinishedMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nclab.chl848.t3android.Message.T3GameFinishedMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code T3GameFinishedMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:T3GameFinishedMessage)
        com.nclab.chl848.t3android.Message.T3GameFinishedMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nclab.chl848.t3android.Message.internal_static_T3GameFinishedMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nclab.chl848.t3android.Message.internal_static_T3GameFinishedMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nclab.chl848.t3android.Message.T3GameFinishedMessage.class, com.nclab.chl848.t3android.Message.T3GameFinishedMessage.Builder.class);
      }

      // Construct using com.nclab.chl848.t3android.Message.T3GameFinishedMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        winnerId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nclab.chl848.t3android.Message.internal_static_T3GameFinishedMessage_descriptor;
      }

      public com.nclab.chl848.t3android.Message.T3GameFinishedMessage getDefaultInstanceForType() {
        return com.nclab.chl848.t3android.Message.T3GameFinishedMessage.getDefaultInstance();
      }

      public com.nclab.chl848.t3android.Message.T3GameFinishedMessage build() {
        com.nclab.chl848.t3android.Message.T3GameFinishedMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.nclab.chl848.t3android.Message.T3GameFinishedMessage buildPartial() {
        com.nclab.chl848.t3android.Message.T3GameFinishedMessage result = new com.nclab.chl848.t3android.Message.T3GameFinishedMessage(this);
        result.winnerId_ = winnerId_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nclab.chl848.t3android.Message.T3GameFinishedMessage) {
          return mergeFrom((com.nclab.chl848.t3android.Message.T3GameFinishedMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nclab.chl848.t3android.Message.T3GameFinishedMessage other) {
        if (other == com.nclab.chl848.t3android.Message.T3GameFinishedMessage.getDefaultInstance()) return this;
        if (other.getWinnerId() != 0) {
          setWinnerId(other.getWinnerId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.nclab.chl848.t3android.Message.T3GameFinishedMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.nclab.chl848.t3android.Message.T3GameFinishedMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int winnerId_ ;
      /**
       * <code>optional int32 winnerId = 1;</code>
       */
      public int getWinnerId() {
        return winnerId_;
      }
      /**
       * <code>optional int32 winnerId = 1;</code>
       */
      public Builder setWinnerId(int value) {
        
        winnerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 winnerId = 1;</code>
       */
      public Builder clearWinnerId() {
        
        winnerId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:T3GameFinishedMessage)
    }

    // @@protoc_insertion_point(class_scope:T3GameFinishedMessage)
    private static final com.nclab.chl848.t3android.Message.T3GameFinishedMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nclab.chl848.t3android.Message.T3GameFinishedMessage();
    }

    public static com.nclab.chl848.t3android.Message.T3GameFinishedMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<T3GameFinishedMessage>
        PARSER = new com.google.protobuf.AbstractParser<T3GameFinishedMessage>() {
      public T3GameFinishedMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new T3GameFinishedMessage(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<T3GameFinishedMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<T3GameFinishedMessage> getParserForType() {
      return PARSER;
    }

    public com.nclab.chl848.t3android.Message.T3GameFinishedMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface T3SwitchPlayerMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:T3SwitchPlayerMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 activePlayerId = 1;</code>
     */
    int getActivePlayerId();
  }
  /**
   * Protobuf type {@code T3SwitchPlayerMessage}
   */
  public  static final class T3SwitchPlayerMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:T3SwitchPlayerMessage)
      T3SwitchPlayerMessageOrBuilder {
    // Use T3SwitchPlayerMessage.newBuilder() to construct.
    private T3SwitchPlayerMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private T3SwitchPlayerMessage() {
      activePlayerId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private T3SwitchPlayerMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              activePlayerId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nclab.chl848.t3android.Message.internal_static_T3SwitchPlayerMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nclab.chl848.t3android.Message.internal_static_T3SwitchPlayerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage.class, com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage.Builder.class);
    }

    public static final int ACTIVEPLAYERID_FIELD_NUMBER = 1;
    private int activePlayerId_;
    /**
     * <code>optional int32 activePlayerId = 1;</code>
     */
    public int getActivePlayerId() {
      return activePlayerId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (activePlayerId_ != 0) {
        output.writeInt32(1, activePlayerId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (activePlayerId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, activePlayerId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code T3SwitchPlayerMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:T3SwitchPlayerMessage)
        com.nclab.chl848.t3android.Message.T3SwitchPlayerMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nclab.chl848.t3android.Message.internal_static_T3SwitchPlayerMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nclab.chl848.t3android.Message.internal_static_T3SwitchPlayerMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage.class, com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage.Builder.class);
      }

      // Construct using com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        activePlayerId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nclab.chl848.t3android.Message.internal_static_T3SwitchPlayerMessage_descriptor;
      }

      public com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage getDefaultInstanceForType() {
        return com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage.getDefaultInstance();
      }

      public com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage build() {
        com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage buildPartial() {
        com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage result = new com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage(this);
        result.activePlayerId_ = activePlayerId_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage) {
          return mergeFrom((com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage other) {
        if (other == com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage.getDefaultInstance()) return this;
        if (other.getActivePlayerId() != 0) {
          setActivePlayerId(other.getActivePlayerId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int activePlayerId_ ;
      /**
       * <code>optional int32 activePlayerId = 1;</code>
       */
      public int getActivePlayerId() {
        return activePlayerId_;
      }
      /**
       * <code>optional int32 activePlayerId = 1;</code>
       */
      public Builder setActivePlayerId(int value) {
        
        activePlayerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 activePlayerId = 1;</code>
       */
      public Builder clearActivePlayerId() {
        
        activePlayerId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:T3SwitchPlayerMessage)
    }

    // @@protoc_insertion_point(class_scope:T3SwitchPlayerMessage)
    private static final com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage();
    }

    public static com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<T3SwitchPlayerMessage>
        PARSER = new com.google.protobuf.AbstractParser<T3SwitchPlayerMessage>() {
      public T3SwitchPlayerMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new T3SwitchPlayerMessage(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<T3SwitchPlayerMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<T3SwitchPlayerMessage> getParserForType() {
      return PARSER;
    }

    public com.nclab.chl848.t3android.Message.T3SwitchPlayerMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_T3PlayerDataMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_T3PlayerDataMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_T3StartNewGameMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_T3StartNewGameMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_T3PlayerMoveMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_T3PlayerMoveMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_T3GameFinishedMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_T3GameFinishedMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_T3SwitchPlayerMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_T3SwitchPlayerMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Messages.proto\";\n\023T3PlayerDataMessage\022" +
      "\022\n\nplayerName\030\001 \001(\t\022\020\n\010playerId\030\002 \001(\005\"-\n" +
      "\025T3StartNewGameMessage\022\024\n\014initPlayerId\030\001" +
      " \001(\005\"8\n\023T3PlayerMoveMessage\022\020\n\010playerId\030" +
      "\001 \001(\005\022\017\n\007tileNum\030\002 \001(\005\")\n\025T3GameFinished" +
      "Message\022\020\n\010winnerId\030\001 \001(\005\"/\n\025T3SwitchPla" +
      "yerMessage\022\026\n\016activePlayerId\030\001 \001(\005B%\n\032co" +
      "m.nclab.chl848.t3androidB\007Messageb\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_T3PlayerDataMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_T3PlayerDataMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_T3PlayerDataMessage_descriptor,
        new java.lang.String[] { "PlayerName", "PlayerId", });
    internal_static_T3StartNewGameMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_T3StartNewGameMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_T3StartNewGameMessage_descriptor,
        new java.lang.String[] { "InitPlayerId", });
    internal_static_T3PlayerMoveMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_T3PlayerMoveMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_T3PlayerMoveMessage_descriptor,
        new java.lang.String[] { "PlayerId", "TileNum", });
    internal_static_T3GameFinishedMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_T3GameFinishedMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_T3GameFinishedMessage_descriptor,
        new java.lang.String[] { "WinnerId", });
    internal_static_T3SwitchPlayerMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_T3SwitchPlayerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_T3SwitchPlayerMessage_descriptor,
        new java.lang.String[] { "ActivePlayerId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
